Skin/urls.py
from django.urls import path
from . import views
app_name = 'Skincare'
urlpatterns = [
    path('Skin', views.Skin, name='Skin'),
    path('', views.home, name='home'),
    path('base', views.base, name='base'),
    path('shop', views.shop, name='shop'),
    path('body', views.body, name='body'),
    path('services', views.services, name='services')
]

Skincare/urls.py
from django.contrib import admin
from django.urls import path,include
urlpatterns = [
    path('', include('Skin.urls')),
    path('admin/', admin.site.urls),

]



Skin/models.py
from django.db import models

# Create your models here.

Skin/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template import loader


def Skin(request):
    return HttpResponse("Skincare is Hereditary")

def base(request):
    template = loader.get_template('base.html')
    return HttpResponse(template.render())

def home(request):
    template = loader.get_template('home.html')
    return HttpResponse(template.render())

def shop(request):
    template = loader.get_template('shop.html')
    return HttpResponse(template.render())
def services(request):
    template = loader.get_template('services.html')
    return HttpResponse(template.render())
def body(request):
    template = loader.get_template('body.html')
    return HttpResponse(template.render())


# Create your views here.

Skin/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Skin</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <style>
        .navbar-custom {
            background-color: transparent;
        }
        .navbar-custom .navbar-brand,
        .navbar-custom .nav-link {
            color: black;
        }
        .navbar-custom .nav-link:hover {
            color: gray;
        }
        .navbar-custom .navbar-toggler-icon {
            filter: invert(1);
        }
    </style>
</head>
<body>
<nav class="navbar navbar-expand-sm navbar-custom">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">
      <img src="{% static 'images/logo.png' %}" alt="Logo" style="width:40px;">
      Sheer Skin
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'Skincare:home' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'Skincare:shop' %}">Shop</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'Skincare:body' %}">Skin</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'Skincare:services' %}">Services</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

Skin/templates/body.html
{% extends 'base.html' %}
{% load static %}
{% block context %}
<title>Skin</title>
    <link rel="stylesheet" href="{%static 'css/style.css' %}">
<img src="{% static 'images/skin.jpg' %}" alt="Skin home image">
{% endblock %}

Skin/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
    <style>
        body {
            background-image: url("{% static 'images/home.jpeg' %}");
            background-size: cover;
            background-repeat: no-repeat;
            background-attachment: fixed;
            background-position: center;
        }
    </style>

{% endblock %}

{% block content %}
    <title>Home</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <h1>Sheer Glow</h1>
    <h1>
Turning dreams into realities, and shaping the future one innovation at a time
</h1>
{% endblock %}



Skin/templates/services.html
{% extends 'base.html' %}
{% block context %}
<title>Our Services</title>

<h1> CLEAN CLINICAL SKINCARE</h1>
    <h3>Mindful and efficacy-driven formulas that deliver sensorial experiences with proven results you can see</h3>

{% endblock %}


Skin/templates/shop.html
{% extends 'base.html' %}
{% block context %}

<title>Home</title>

<h1>Sheer Glow</h1>

{% endblock %}